Mask password
satisfactorymodding/SatisfactoryModManager pull request #190
Opened 2024-02-28 05:39 UTC by elightcap

Mask password in Server Connections.  Password is masked by default, with a button to show the password. This is only in the basic mode, im not sure if there would be a way to just mask the password in the connection string for the advanced mode

2024-03-01 15:07 UTC, budak7273 commented
Perhaps advanced mode could have a warning box near it that says "your server password is potentially displayed while on this screen" or similar

2024-03-01 22:38 UTC, mircearoata requested changes
The passwords are also visible in the server list, so those should be redacted too. I don't think that they should be controlled by the same hide/show button as the password input, though, maybe clicking on each of them would show/hide that single unredacted URL.

Hovering over the folder icon in the install combobox also displays the full URL, though, as I understand it, the purpose of this PR is to ensure the credentials aren't leaked through screenshots or someone looking at your screen, so those are probably fine to remain unredacted.

As for the advanced mode, a note could work, but imo it's pretty clear that there's going to be a plaintext password in there already. The advanced mode is also only meant as a backup, just in case there's somehow some field that the simple mode doesn't support, which shouldn't be the case.

2024-03-01 22:38 UTC, mircearoata commented on frontend/src/lib/components/modals/ServerManager.svelte
> +          {/if}
This could use a comment explaining that `type` can't be dynamic when using `bind:value`

2024-03-05 06:15 UTC, elightcap commented on frontend/src/lib/components/modals/ServerManager.svelte
> +        disabled={addInProgress}
because I'm admittedly not great with html and i copied it from another :)
fixed in d634ead7ca41f744de06c88ca665c3d26c8dd889

2024-03-05 06:15 UTC, elightcap commented on frontend/src/lib/components/modals/ServerManager.svelte
> +              type="password"
added in 50a1c6e0bf3f8a51e3405bea1c896a08fdfb5852

2024-03-08 17:48 UTC, elightcap commented on frontend/src/lib/components/modals/ServerManager.svelte
> +              type="password"
my bad, [2622382](https://github.com/satisfactorymodding/SatisfactoryModManager/pull/190/commits/2622382ea17c2a462712d6a75e230c2f593ac5b9)

2024-03-08 19:04 UTC, mircearoata commented
The new commits do address the code comments, but the point about the password in existing remote installs listed still stands.

2024-06-10 15:59 UTC, mircearoata approved these changes

2024-06-10 15:59 UTC, merged