Improved "generate debug log" flow
satisfactorymodding/SatisfactoryModManager pull request #212
Opened 2024-09-01 22:04 UTC by budak7273

- Now the user must generate a debug log before they can click on the discord invite (hopefully cut down on people screenshotting the error without attaching the file)
- Error handling for when the debug log fails to generate for some reason
- Deduplicated error code between the modal and mods-list-replacer variants

![image](https://github.com/user-attachments/assets/0a5f1ac7-519a-476e-b7e9-258eae236ede)
![image](https://github.com/user-attachments/assets/73f30c79-5f87-44f3-b504-022bb3394f2f)
![image](https://github.com/user-attachments/assets/faf6b483-e21b-4932-b127-51b42915cd6d)

2024-09-02 15:15 UTC, mircearoata requested changes
The button placement looks a bit strange in the non full-page version, I think moving them to the bottom right or left of the dialog, like the debug info button was before, would be better

2024-09-02 15:15 UTC, mircearoata commented on frontend/src/lib/components/modals/ErrorDetails.svelte
> +  });
```suggestion
  const { t } = getTranslate();
  $: openDiscordTooltipText = $t(
    'error.open_modding_discord.must_generate_debug_first',
    'You must generate debug info first',
  );
```

2024-09-02 15:15 UTC, mircearoata commented on frontend/src/lib/components/modals/ErrorDetails.svelte
> +  export let parent: { onClose: () => void };
Could take just onClose instead of the skeleton modal type, and also could be turned nullable to not have to pass it from the invalid installs error

2024-09-03 19:59 UTC, budak7273 commented
![image](https://github.com/user-attachments/assets/5cdd4987-8bb6-4abe-8ef3-2f540f370e32)

2024-09-03 20:22 UTC, mircearoata requested changes

2024-09-03 20:22 UTC, mircearoata commented on frontend/src/lib/components/modals/ErrorDetails.svelte
> +      LogError(`GenerateDebugInfo failed: ${error}`);
LogError passes that back to the backend, but that already logs the error

2024-09-03 20:22 UTC, mircearoata commented on frontend/src/lib/components/modals/ErrorDetails.svelte
> +    <!-- Must lambda the onClose call for type matching to be happy -->
No longer applies

2024-09-03 20:22 UTC, mircearoata commented on backend/app/debug_info.go
> +		return false, err
```suggestion
		return false, fmt.Errorf("failed to open save dialog: %w", err)
```

2024-09-03 20:22 UTC, mircearoata commented on backend/app/debug_info.go
> +		return false, err
```suggestion
		return false, fmt.Errorf("failed to generate debug info: %w", err)
```

2024-09-03 21:59 UTC, mircearoata approved these changes

2024-09-03 22:00 UTC, merged